services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ainhoa
      MYSQL_DATABASE: comparador_de_precios
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
